export const IMAGE_UPLOAD_REQUEST = "IMAGE_UPLOAD_REQUEST";
export const IMAGE_UPLOAD_SUCCESS = "IMAGE_UPLOAD_SUCCESS";
export const IMAGE_UPLOAD_FAIL = "IMAGE_UPLOAD_FAIL";

export const IMAGE_RETRIEVE_REQUEST = "IMAGE_RETRIEVE_REQUEST";
export const IMAGE_RETRIEVE_SUCCESS = "IMAGE_RETRIEVE_SUCCESS";
export const IMAGE_RETRIEVE_FAIL = "IMAGE_RETRIEVE_FAIL";

export const IMAGE_UPLOAD_CLEAR = "IMAGE_UPLOAD_CLEAR";
export const IMAGE_RETRIEVE_CLEAR = "IMAGE_RETRIEVE_CLEAR";