export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_SIGNOUT = 'USER_SIGNOUT';

export const SEND_EMAIL_VERIFICATION_LINK_REQUEST = "SEND_EMAIL_VERIFICATION_LINK_REQUEST";
export const SEND_EMAIL_VERIFICATION_LINK_SUCCESS = "SEND_EMAIL_VERIFICATION_LINK_SUCCESS";
export const SEND_EMAIL_VERIFICATION_LINK_FAIL = "SEND_EMAIL_VERIFICATION_LINK_FAIL";

export const IS_EMAIL_VERIFIED_REQUEST = "IS_EMAIL_VERIFIED_REQUEST";
export const IS_EMAIL_VERIFIED_SUCCESS = "IS_EMAIL_VERIFIED_SUCCESS";
export const IS_EMAIL_VERIFIED_FAIL = "IS_EMAIL_VERIFIED_FAIL";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const PASSWORD_RESET_REQUEST = "PASSWORD_RESET_REQUEST";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_FAIL = "PASSWORD_RESET_FAIL";

export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";
export const CLEAR_CHANGE_PASSWORD_STATE = "CLEAR_CHANGE_PASSWORD_STATE";

export const AUTHORIZE_REQUEST = "AUTHORIZE_REQUEST";
export const AUTHORIZE_SUCCESS = "AUTHORIZE_SUCCESS";
export const AUTHORIZE_FAIL = "AUTHORIZE_FAIL";
export const CLEAR_AUTHORIZE_INFO = "CLEAR_AUTHORIZE_INFO";